-- CreateTable
CREATE TABLE "CompanySettings" (
    "id" TEXT NOT NULL,
    "nomEntreprise" TEXT NOT NULL DEFAULT 'Mon Entreprise',
    "formeJuridique" TEXT,
    "logoPath" TEXT,
    "adresse" TEXT,
    "codePostal" TEXT,
    "ville" TEXT,
    "pays" TEXT DEFAULT 'Algérie',
    "telephone" TEXT,
    "fax" TEXT,
    "email" TEXT,
    "siteWeb" TEXT,
    "rc" TEXT,
    "nif" TEXT,
    "ai" TEXT,
    "nis" TEXT,
    "compteBancaire" TEXT,
    "rib" TEXT,
    "banque" TEXT,
    "devisePrincipale" TEXT NOT NULL DEFAULT 'DZD',
    "tauxTVADefaut" DOUBLE PRECISION NOT NULL DEFAULT 19,
    "prefixDevis" TEXT NOT NULL DEFAULT 'DV',
    "prefixCommande" TEXT NOT NULL DEFAULT 'CMD',
    "prefixFacture" TEXT NOT NULL DEFAULT 'FAC',
    "prefixAvoir" TEXT NOT NULL DEFAULT 'AV',
    "prefixCommandeFournisseur" TEXT NOT NULL DEFAULT 'CF',
    "prefixFactureFournisseur" TEXT NOT NULL DEFAULT 'FF',
    "prefixCharge" TEXT NOT NULL DEFAULT 'CHG',
    "prefixClient" TEXT NOT NULL DEFAULT 'CLI',
    "prefixFournisseur" TEXT NOT NULL DEFAULT 'FOU',
    "prefixProspect" TEXT NOT NULL DEFAULT 'PRO',
    "prefixProduit" TEXT NOT NULL DEFAULT 'PRD',
    "prefixService" TEXT NOT NULL DEFAULT 'SRV',
    "longueurNumero" INTEGER NOT NULL DEFAULT 5,
    "inclureAnnee" BOOLEAN NOT NULL DEFAULT true,
    "separateur" TEXT NOT NULL DEFAULT '-',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CompanySettings_pkey" PRIMARY KEY ("id")
);
